### ISSUE TITLE
[BUG] Unable to save data map - version 1.2022.3.1

### ISSUE THREAD

**Issue by mah87** [LinkeD365/MockarooDataMunger#26]
I have a custom table (called "Application") that has a lookup to Account table. When I configure the datamunger to generate mock data with a "fixed lookup" for account field (as seen in the attached snapshot), I am able to generate the rows, however, the tool throws the following error when I try to save the map.

"There was an error generating the XML document" 

System.Exception: Error while serializing: There was an error generating the XML document.
   at McTools.Xrm.Connection.XmlSerializerHelper.SerializeToFile(Object o, String path)
   at LinkeD365.MockDataGen.MockDataGenCtl.ShowSaveMap()
   at LinkeD365.MockDataGen.MockDataGenCtl.btnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)

XTB version: 1.2022.11.59
Mockaroo Data Munger: 1.2022.3.1

**Screenshots**
![image](https://user-images.githubusercontent.com/1092923/211167515-0cc42550-6b6b-49ab-85dd-eebbd3d3d0e4.png)

The same behaviour is happening with OOB tables as well

**Comment by LinkeD365** [comment]
Just getting to this, sorry for delayl
