### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by pab74** [LinkeD365/MockarooDataMunger#7]
Hello, I am trying your xrmtoolbox. Looks useful, but I am facing several problems. I found out that 99% of the time if you map a field and then modify or unmap it, then the plugin crashes. In my last attempt I added the currency field, set to "fixed lookup", then I unmapped it and it crashed. At this point the xml setting file failed to load because it was malformed. and so the plugin failed to start. I fixed it manually, reloaded the plugin and now I have the following error:
************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinkeD365.MockDataGen.Mock.Country.PopulateFromKVP(List`1 kvps)
   at LinkeD365.MockDataGen.MockDataGenCtl.<>c__DisplayClass0_0.<BuildGrid>b__3(RunWorkerCompletedEventArgs e)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
In any case, nice job, thank you for sharing
Kind regards
Paolo

**Comment by LinkeD365** [comment]
I think I have resolved this, as it was due to like you say the file that got generated. Can you try the latest version 8.7 @pab74 ?
